<?php
/******* Custom Post type for Beers ***********/
add_action ('init', 'create_beer_posttype');
if (!function_exists('create_beer_posttype')) {
	function create_beer_posttype() {

		register_post_type( 'utb_beer',
		    array (
		      'labels' => array(
		        'name' => __( 'Ales', 'utb_utbdom' ),
		        'singular_name' => __( 'Ale', 'utb_utbdom' )
		    ),
		      'taxonomies' => array('category', 'post_tag'),
		      'public' => true,
		      'has_archive' => true,
		      'supports' => array( 'title', 'editor', 'excerpt', 'custom-fields', 'thumbnail' ),
		      'rewrite' => array('slug' => 'ale'),
		)   );

	}
}
/* meta boxes for the utb_beer create_beer_posttype */

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function beer_info_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function beer_info_add_meta_box() {
	add_meta_box(
		'beer_info-beer-info',
		__( 'Beer Info', 'beer_info' ),
		'beer_info_html',
		'post',
		'normal',
		'default'
	);
	add_meta_box(
		'beer_info-beer-info',
		__( 'Beer Info', 'beer_info' ),
		'beer_info_html',
		'utb_beer',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'beer_info_add_meta_box' );

function beer_info_html( $post) {
	wp_nonce_field( '_beer_info_nonce', 'beer_info_nonce' ); ?>

	<p>More info about the beer</p>

	<p>
		<label for="beer_info_label_image_url"><?php _e( 'Label Image URL', 'beer_info' ); ?></label><br>
		<input type="text" name="beer_info_label_image_url" id="beer_info_label_image_url" value="<?php echo beer_info_get_meta( 'beer_info_label_image_url' ); ?>">
	</p>	<p>

		<input type="checkbox" name="beer_info_display_label_with_title" id="beer_info_display_label_with_title" value="display-label-with-title" <?php echo ( beer_info_get_meta( 'beer_info_display_label_with_title' ) === 'display-label-with-title' ) ? 'checked' : ''; ?>>
		<label for="beer_info_display_label_with_title"><?php _e( 'Display label next to title', 'beer_info' ); ?></label>	</p><?php
}

function beer_info_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['beer_info_nonce'] ) || ! wp_verify_nonce( $_POST['beer_info_nonce'], '_beer_info_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['beer_info_label_image_url'] ) )
		update_post_meta( $post_id, 'beer_info_label_image_url', esc_attr( $_POST['beer_info_label_image_url'] ) );
	if ( isset( $_POST['beer_info_display_label_with_title'] ) )
		update_post_meta( $post_id, 'beer_info_display_label_with_title', esc_attr( $_POST['beer_info_display_label_with_title'] ) );
	else
		update_post_meta( $post_id, 'beer_info_display_label_with_title', null );
}
add_action( 'save_post', 'beer_info_save' );

/*
	Usage: beer_info_get_meta( 'beer_info_label_image_url' )
	Usage: beer_info_get_meta( 'beer_info_display_label_with_title' )
*/

?>
